name: Documentation

on:
    push:
        branches: [main]
        paths:
            - "src/**"
            - "package-lock.json"
            - "package.json"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"

            - run: npm install -g documentation

            - run: documentation build src/index.js -f html --github -o docs

            - name: Commit
              run: |
                  git config --global user.email "bot@williamharrison.dev"
                  git config --global user.name "WDH-Bot"
                  git add docs/**
                  git commit -m "feat: build docs"
                  git push
